"""empty message

Revision ID: 062d7712afd3
Revises: 214a42e071b9
Create Date: 2024-04-22 11:52:39.971400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062d7712afd3'
down_revision = '214a42e071b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clientname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clientname')

    # ### end Alembic commands ###
