"""empty message

Revision ID: 101d53a68061
Revises: 7d82791f0699
Create Date: 2024-04-19 20:20:33.823346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101d53a68061'
down_revision = '7d82791f0699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.alter_column('clientid',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.alter_column('clientid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
