"""empty message

Revision ID: 214a42e071b9
Revises: 0a1387e78c59
Create Date: 2024-04-22 11:17:32.636753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214a42e071b9'
down_revision = '0a1387e78c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.drop_column('unique_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_code', sa.VARCHAR(length=12), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
