"""empty message

Revision ID: 252f957f633d
Revises: e57513662b32
Create Date: 2024-04-16 20:38:27.477808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252f957f633d'
down_revision = 'e57513662b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clientname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.drop_column('clientname')

    # ### end Alembic commands ###
