"""empty message

Revision ID: 25b74c03536b
Revises: 4eec5209ea4a
Create Date: 2024-04-17 07:56:56.084138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b74c03536b'
down_revision = '4eec5209ea4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dependant_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_5', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medial_amount', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('medial_amount')
        batch_op.drop_column('dependant_5')
        batch_op.drop_column('dependant_4')
        batch_op.drop_column('dependant_3')
        batch_op.drop_column('dependant_2')
        batch_op.drop_column('dependant_1')

    # ### end Alembic commands ###
