"""empty message

Revision ID: 2982bbe94c0f
Revises: 24cf4e714634
Create Date: 2024-04-17 16:43:24.145400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2982bbe94c0f'
down_revision = '24cf4e714634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staffunique_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('staffunique_code')

    # ### end Alembic commands ###
