"""empty message

Revision ID: 411874999d3a
Revises: d3b6ad426654
Create Date: 2024-04-08 01:51:34.278800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411874999d3a'
down_revision = 'd3b6ad426654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('unique_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('unique_code',
               existing_type=sa.String(length=12),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
