"""empty message

Revision ID: 4eec5209ea4a
Revises: 9d7dbfda0538
Create Date: 2024-04-17 07:38:23.063092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eec5209ea4a'
down_revision = '9d7dbfda0538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clientid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('clientid')

    # ### end Alembic commands ###
