"""empty message

Revision ID: 634a5e80fe33
Revises: 252f957f633d
Create Date: 2024-04-16 21:15:50.291526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634a5e80fe33'
down_revision = '252f957f633d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
