"""empty message

Revision ID: 7d82791f0699
Revises: 9e43070bde3b
Create Date: 2024-04-19 20:15:31.348113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d82791f0699'
down_revision = '9e43070bde3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clientid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('clientname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clientid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('clientname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('staffname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('staffunique_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('userid', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clientid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dependant_5', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medial_amount', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('medial_amount')
        batch_op.drop_column('dependant_5')
        batch_op.drop_column('dependant_4')
        batch_op.drop_column('dependant_3')
        batch_op.drop_column('dependant_2')
        batch_op.drop_column('dependant_1')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('clientid')

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('userid')
        batch_op.drop_column('staffunique_code')
        batch_op.drop_column('staffname')
        batch_op.drop_column('clientname')
        batch_op.drop_column('clientid')

    with op.batch_alter_table('cisl', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('status')
        batch_op.drop_column('clientname')
        batch_op.drop_column('clientid')

    # ### end Alembic commands ###
