"""empty message

Revision ID: acc5c5d4ded2
Revises: fc3f29d474ed
Create Date: 2024-05-03 01:57:09.950819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc5c5d4ded2'
down_revision = 'fc3f29d474ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_album', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('indexnumber', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ask', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cisl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientid', sa.String(), nullable=True),
    sa.Column('clientname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('incident', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('casualties', sa.String(), nullable=True),
    sa.Column('employees', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('police', sa.String(), nullable=True),
    sa.Column('fire_force', sa.String(), nullable=True),
    sa.Column('claim', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('name_of_contact', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('schools', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('pdf_filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('createclient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('unique_code', sa.String(length=12), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('image_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('getfunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('ministry', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(), nullable=True),
    sa.Column('clientid', sa.String(), nullable=True),
    sa.Column('clientname', sa.String(), nullable=True),
    sa.Column('staffname', sa.String(), nullable=True),
    sa.Column('staffunique_code', sa.String(), nullable=True),
    sa.Column('userid', sa.String(), nullable=True),
    sa.Column('idcard', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('expense', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('directress', sa.String(), nullable=True),
    sa.Column('others', sa.String(), nullable=True),
    sa.Column('ministries', sa.String(), nullable=True),
    sa.Column('total_number', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('future', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('implementation', sa.String(), nullable=True),
    sa.Column('challenges', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('unique_code', sa.String(length=12), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('image_file', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('confirm_password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('departments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=True),
    sa.Column('studentID', sa.String(), nullable=True),
    sa.Column('studentnumber', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studenthalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=True),
    sa.Column('regno', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hallname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('clientid', sa.String(), nullable=True),
    sa.Column('clientname', sa.String(), nullable=True),
    sa.Column('staff_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('dependant_1', sa.String(), nullable=True),
    sa.Column('dependant_2', sa.String(), nullable=True),
    sa.Column('dependant_3', sa.String(), nullable=True),
    sa.Column('dependant_4', sa.String(), nullable=True),
    sa.Column('dependant_5', sa.String(), nullable=True),
    sa.Column('medial_amount', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('unique_code', sa.String(length=12), nullable=True),
    sa.Column('qualities', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('image_file', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('date_completed', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='ft_item_group_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_file')
    op.drop_table('item')
    op.drop_table('work')
    op.drop_table('waitlist')
    op.drop_table('user')
    op.drop_table('studenthalls')
    op.drop_table('student_data')
    op.drop_table('school')
    op.drop_table('program')
    op.drop_table('person')
    op.drop_table('message')
    op.drop_table('logger')
    op.drop_table('leaders')
    op.drop_table('hospital')
    op.drop_table('groups')
    op.drop_table('getfunds')
    op.drop_table('faq')
    op.drop_table('department')
    op.drop_table('createclient')
    op.drop_table('course')
    op.drop_table('committee')
    op.drop_table('cisl')
    op.drop_table('challenges')
    op.drop_table('challenge')
    op.drop_table('budget')
    op.drop_table('ask')
    op.drop_table('alumni')
    op.drop_table('album')
    # ### end Alembic commands ###
