"""empty message

Revision ID: d5764d91c8fa
Revises: 30cd5a690675
Create Date: 2024-04-12 14:06:13.339960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5764d91c8fa'
down_revision = '30cd5a690675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idcard', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('expense', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital')
    # ### end Alembic commands ###
